
name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup authentication
      run:  |
        echo token: ${TOKEN}
        echo other: ${{ github.token }}
        echo upper: ${{ secrets.GITHUB_TOKEN }}
        echo lower: ${{ secrets.github_token }}
        tee .auth <<< "-H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' "
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build with make
      run:  make -C . -j 1
    - name: Move manifests next to binaries
      run:  mv -vf *.json bin/
    - name: Archive and compress target
      run:  tar -czvf binaries.tgz -C bin .
    - name: Upload built directory
      uses: actions/upload-artifact@v2
      with:
        name: k8s-tools
        path: ./binaries.tgz
