
name: CI

on:
  push:
    tags:
    - v*
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup authentication
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:  |
        git config github.user "x-access-token"
        git config github.pat "${TOKEN}"
        git config --get-regexp ^github
    - name: Build with make
      run:  make -C . -j 1
    - name: Move manifests next to binaries
      run:  mv -vf *.json bin/
    - name: Archive and compress target
      run:  tar -czvf binaries.tgz -C bin .
    - name: Create a draft release
      uses: actions/create-release@v1
      id: release
      if: ${{ ! startsWith(github.ref, 'refs/heads/') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Automatic Release at ${{ github.ref }}
        prerelease: true
        draft: true
    - name: Upload assets for release
      uses: actions/upload-release-asset@v1
      if: ${{ ! startsWith(github.ref, 'refs/heads/') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_name: k8s-tools.tar.gz
        asset_path: ./binaries.tgz
        asset_content_type: application/x-tar
    - name: Upload build archive
      uses: actions/upload-artifact@v2
      with:
        name: k8s-tools.tgz
        path: ./binaries.tgz
        retention-days: 360
        if-no-files-found: error

